name: PR
on: [pull_request]
jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
    - name: Chekout Repository
      uses: actions/checkout@v3

    - name: Install Node.JS v19
      uses: actions/setup-node@v3
      with:
        node-version: 19

    - run: yarn install --frozen-lockfile

    - name: Compile TypeScript
      run: yarn build:ci

    - name: Lint
      run: yarn lint
